@Api_HostAddress = http://localhost:5199

GET {{Api_HostAddress}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmZmEyMmY5Ni01OGE1LTRkY2QtODg2Mi00MGZlZWU3YTg0ODkiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwianRpIjoiYTZjMDE1NWUtMmE3OC00OTlhLWIxZjYtNDczZTBmZjZmNTA3IiwiZXhwIjoxNzE3NTA5NTYxLCJpc3MiOiJCdWJhRWF0cyIsImF1ZCI6IkJ1YmFFYXRzIn0.ekUKyiFSw_3bTVLR010f8o_eeN_M5aiBL3AgtOnAx7Q